spring.application.name=report_service

# 1. Server Configuration
server.port=8088

# 2. R2DBC Database Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/report_service
spring.r2dbc.username=postgres
spring.r2dbc.password=0608
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20

# 3. Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=report-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=mn.num.edu.report_service.domain.event
spring.kafka.consumer.properties.spring.json.use.type.headers=false
#spring.kafka.consumer.properties.spring.json.value.default.type=mn.num.edu.grading_service.domain.event.StudentRegisteredEvent

# Topics
#kafka.topic.thesis-created=thesis-created
#kafka.topic.thesis-updated=thesis-updated
#kafka.topic.thesis-approved=thesis-approved
#kafka.topic.thesis-rejected=thesis-rejected
#kafka.topic.thesis-status-changed=thesis-status-changed
#kafka.topic.user-created=user-created-events
#kafka.topic.student-assigned=committee-student-assigned

# 4. Jackson
spring.jackson.default-property-inclusion=non_null

# Logging
logging.level.root=INFO
logging.level.org.springframework.r2dbc.core=WARN
logging.level.org.springframework.data.r2dbc.core=WARN
logging.level.org.springframework.data.r2dbc=WARN
logging.level.reactor.kafka=WARN
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
logging.level.mn.num.edu.grading_service=INFO