spring.application.name=evaluation_service

server.port=8085

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/evaluation_service
spring.r2dbc.username=postgres
spring.r2dbc.password=0608
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20

spring.kafka.bootstrap-servers=localhost:9092

# producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# consumer
spring.kafka.consumer.group-id=evaluation-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# topics
workflow.topic.created=workflow-created
workflow.topic.stage-created=workflow-stage-created
workflow.topic.stage-activated=workflow-stage-activated
workflow.topic.stage-closed=workflow-stage-closed
workflow.topic.completed=workflow-completed

workflow.topic.thesis-approved=thesis-approved
workflow.topic.committee-created=committee-created
workflow.topic.report-submitted=report-submitted
workflow.topic.evaluation-submitted=evaluation-submitted

spring.jackson.default-property-inclusion=non_null

logging.level.root=INFO
logging.level.org.springframework.r2dbc.core=WARN
logging.level.org.springframework.data.r2dbc.core=WARN
logging.level.org.springframework.data.r2dbc=WARN
logging.level.reactor.kafka=WARN
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
logging.level.mn.num.edu.workflow_service=INFO